##################
# 基本连接池配置
##################

# 数据源名称，给数据源起个名字
druid.name=handtomcatDatasource

# 数据库的 JDBC 驱动类，通常是数据库厂商提供的 JDBC 驱动
druid.driverClassName=com.mysql.cj.jdbc.Driver

# 数据库的连接 URL
druid.url=jdbc:mysql://127.0.0.1:3306/handtomcat?useSSL=false&serverTimezone=UTC

# 数据库连接用户名
druid.username=root

# 数据库连接密码
druid.password=Carey_31

#########################
# 连接池的大小配置
#########################

# 初始化连接池时的连接数，默认是 0
druid.initialSize=5

# 最小空闲连接数，表示连接池在空闲时最小连接数
druid.minIdle=5

# 最大连接数，表示连接池中最大可以拥有的连接数
druid.maxActive=20

# 获取连接的最大等待时间，单位是毫秒
druid.maxWait=60000

# 配置获取连接时是否检查连接是否有效（例如，通过 SQL `SELECT 1` 进行验证）
druid.testOnBorrow=true

# 配置连接池在空闲时检测连接是否有效
druid.testWhileIdle=true

# 配置连接是否能够被回收
druid.removeAbandoned=true

# 连接空闲时的最大时间（超过该时间会被回收）
druid.removeAbandonedTimeout=1800
